name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: List directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "\nContents:"
          ls -la
          echo "\nNext directory:"
          ls -la .next
          echo "\nNext static directory:"
          ls -la .next/static

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/**/*
            public/**/*
          if-no-files-found: error

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: List directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "\nContents:"
          ls -la
          echo "\nNext directory:"
          ls -la .next || true
          echo "\nNext static directory:"
          ls -la .next/static || true

      - name: Prepare Vercel build output
        run: |
          mkdir -p .vercel/output/static
          mkdir -p .vercel/output/_next/static
          
          if [ -d ".next/static" ]; then
            cp -r .next/static/* .vercel/output/static/
            cp -r .next/static/* .vercel/output/_next/static/
          fi
          
          if [ -d "public" ]; then
            cp -r public/* .vercel/output/static/
          fi
          
          echo '{ "version": 3 }' > .vercel/output/config.json
          
          if [ -d ".next/standalone" ]; then
            cp -r .next/standalone/* .vercel/output/
          fi
          
          if [ -d ".next/server" ]; then
            cp -r .next/server .vercel/output/
          fi
          
          echo "Vercel output directory:"
          ls -la .vercel/output

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  test-production:
    needs: deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for deployment
        run: sleep 30  # Aguarda 30 segundos para garantir que o deploy foi propagado

      - name: Run Checkly tests
        run: npx checkly test
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
